---
id: hordectl
name: Hordectl
full: Scenario deployer library
description: A setup utility for manipulating horde application contents.
list: dev
type: library
homepage: https://www.horde.org
authors:
  -
    name: Ralf Lang
    user: rlang
    email: lang@b1-systems.de
    active: true
    role: lead
version:
  release: 1.0.0
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_Injector: ^2
